image: epitechcontent/epitest-docker

build:
  stage: build
  script:
    - make -j 4
  artifacts:
      paths:
        - ./*.a
        - ./*.so

# need some tests scripts :3
test:
  stage: test
  script:
    - ./tests/gitlab_ci_test.sh
  dependencies:
    - build

